name: ticketing-api
region: nyc
services:
- name: api
  github:
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
    deploy_on_push: true
  build_command: npm run build
  run_command: npm start
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /healthz
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 3
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: API_PREFIX
    value: /api
  - key: SWAGGER_ENABLED
    value: "true"
databases:
- name: ticketing-db
  engine: MYSQL
  version: "8"
  size: db-s-1vcpu-1gb
  num_nodes: 1