export const ERR = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_INACTIVE: 'PRODUCT_INACTIVE',
  SOLD_OUT: 'SOLD_OUT',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  COUPON_INVALID: 'COUPON_INVALID',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED'
} as const;

export type ErrorCode = typeof ERR[keyof typeof ERR];

export const ERROR_STATUS_MAP: Record<ErrorCode, number> = {
  [ERR.VALIDATION_ERROR]: 422,
  [ERR.PRODUCT_NOT_FOUND]: 404,
  [ERR.PRODUCT_INACTIVE]: 422,
  [ERR.SOLD_OUT]: 422,
  [ERR.IDEMPOTENCY_CONFLICT]: 409,
  [ERR.TOKEN_EXPIRED]: 401,
  [ERR.UNAUTHORIZED]: 401,
  [ERR.COUPON_INVALID]: 422,
  [ERR.ORDER_NOT_FOUND]: 404,
  [ERR.PAYMENT_FAILED]: 400
};